showGrid: false

url: http://www.thecave.com
title: thecave | Ramblings From A Crotchety Old Man
author: Kirby Turner

root: /

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section

permalink: /:year/:month/:day/:title/

# Twitter
twitter_user: whitepeak
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true


# Category plugin (https://github.com/recurser/jekyll-plugins)
category_dir: category
